# Generated by Django 5.0.4 on 2024-05-10 23:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term')], default='short_term', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('impact', models.CharField(max_length=300)),
                ('created', models.DateField(auto_now_add=True)),
                ('projected', models.DateField(default=None, null=True)),
                ('time_spent', models.DurationField(blank=True, default=None, null=True)),
                ('slug', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now=True)),
                ('pomodoros', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('days', models.ManyToManyField(to='tracker.day')),
                ('objective', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.objective')),
            ],
        ),
    ]
