# Generated by Django 4.2.10 on 2024-03-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_objective_habit_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('Su', 'Sunday'), ('Sa', 'Saturday'), ('Th', 'Thursday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('F', 'Friday'), ('M', 'Monday')], max_length=10, null=True),
        ),
    ]
