# Generated by Django 4.2.10 on 2024-03-30 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_habit_frequency_habit_friday_habit_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='pomodoros',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
