# Generated by Django 4.2.10 on 2024-03-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_objective_time_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='time_spent',
        ),
    ]
