# Generated by Django 4.2.10 on 2024-03-31 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_objective_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
