# Generated by Django 4.2.10 on 2024-03-31 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_objective_time_spent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objective',
            old_name='time_spent',
            new_name='timeSpent',
        ),
    ]
