# Generated by Django 4.2.10 on 2024-04-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_remove_objective_timespent_objective_time_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='description',
            new_name='impact',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='objective',
            name='projected',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='time_spent',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='days',
            field=models.ManyToManyField(to='tracker.day'),
        ),
    ]
