# Generated by Django 4.2.10 on 2024-04-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_day_rename_description_objective_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='term',
            field=models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term')], default='short_term', max_length=20),
        ),
    ]
